// GENERATED CODE! DO NOT MODIFY BY HAND!

// Generated by Codex CLI 0.146.0 (`codex app-server generate-ts`).

/** An absolute, normalized path from the app-server protocol. */
export type AbsolutePathBuf = string;
