// GENERATED CODE! DO NOT MODIFY BY HAND!

// Generated by Codex CLI 0.147.0 (`codex app-server generate-ts`).

import type { AbsolutePathBuf } from './AbsolutePathBuf.js';

export type InitializeResponse = {
  userAgent: string;
  /** Absolute path to the server's CODEX_HOME directory. */
  codexHome: AbsolutePathBuf;
  /** Runtime target family, for example `unix` or `windows`. */
  platformFamily: string;
  /** Runtime operating system, for example `macos`, `linux`, or `windows`. */
  platformOs: string;
};
