// GENERATED CODE! DO NOT MODIFY BY HAND!

// Generated by Codex CLI 0.147.0 (`codex app-server generate-ts`).

/** Client-declared capabilities negotiated during initialize. */
export type InitializeCapabilities = {
  /** Opt into receiving experimental API methods and fields. */
  experimentalApi: boolean;
  /** Opt into `attestation/generate` requests. */
  requestAttestation: boolean;
  /** Allow downstream MCP servers to request extended form elicitations. */
  mcpServerOpenaiFormElicitation?: boolean;
  /** Exact notification method names suppressed for this connection. */
  optOutNotificationMethods?: Array<string> | null;
};
