// GENERATED CODE! DO NOT MODIFY BY HAND!

// Generated by Codex CLI 0.147.0 (`codex app-server generate-ts`).

import type { ClientInfo } from './ClientInfo.js';
import type { InitializeCapabilities } from './InitializeCapabilities.js';

export type InitializeParams = {
  clientInfo: ClientInfo;
  capabilities: InitializeCapabilities | null;
};
