// GENERATED CODE! DO NOT MODIFY BY HAND!

// Generated by Codex CLI 0.147.0 (`codex app-server generate-ts`).

/** Canonical user-input modality tags advertised by a model. */
export type InputModality = 'text' | 'image' | 'audio';
