// GENERATED CODE! DO NOT MODIFY BY HAND!

// Generated by Codex CLI 0.147.0 (`codex app-server generate-ts`).

export type ModelListParams = {
  /** Opaque pagination cursor returned by a previous call. */
  cursor?: string | null;
  /** Optional page size. */
  limit?: number | null;
  /** Include entries hidden from the default picker. */
  includeHidden?: boolean | null;
};
