// GENERATED CODE! DO NOT MODIFY BY HAND!

// Generated by Codex CLI 0.147.0 (`codex app-server generate-ts`).

export type ModelUpgradeInfo = {
  model: string;
  upgradeCopy: string | null;
  modelLink: string | null;
  migrationMarkdown: string | null;
};
