// GENERATED CODE! DO NOT MODIFY BY HAND!

// Generated by Codex CLI 0.146.0 (`codex app-server generate-ts`).

import type { Model } from './Model.js';

export type ModelListResponse = {
  data: Array<Model>;
  /** Opaque cursor for the next page, or null after the last page. */
  nextCursor: string | null;
};
