// GENERATED CODE! DO NOT MODIFY BY HAND!

// Generated by Codex CLI 0.147.0 (`codex app-server generate-ts`).

import type { InputModality } from './InputModality.js';
import type { ReasoningEffort } from './ReasoningEffort.js';
import type { ModelAvailabilityNux } from './ModelAvailabilityNux.js';
import type { ModelServiceTier } from './ModelServiceTier.js';
import type { ModelUpgradeInfo } from './ModelUpgradeInfo.js';
import type { ReasoningEffortOption } from './ReasoningEffortOption.js';

export type Model = {
  id: string;
  model: string;
  upgrade: string | null;
  upgradeInfo: ModelUpgradeInfo | null;
  availabilityNux: ModelAvailabilityNux | null;
  displayName: string;
  description: string;
  hidden: boolean;
  supportedReasoningEfforts: Array<ReasoningEffortOption>;
  defaultReasoningEffort: ReasoningEffort;
  inputModalities: Array<InputModality>;
  supportsPersonality: boolean;
  /** Deprecated: use `serviceTiers` instead. */
  additionalSpeedTiers: Array<string>;
  serviceTiers: Array<ModelServiceTier>;
  /** Catalog default service tier id for this model, when configured. */
  defaultServiceTier: string | null;
  isDefault: boolean;
};
