// GENERATED CODE! DO NOT MODIFY BY HAND!

// Generated by Codex CLI 0.146.0 (`codex app-server generate-ts`).

import type { ReasoningEffort } from './ReasoningEffort.js';

export type ReasoningEffortOption = {
  reasoningEffort: ReasoningEffort;
  description: string;
};
