// GENERATED CODE! DO NOT MODIFY BY HAND!

// Generated by Codex CLI 0.146.0 (`codex app-server generate-ts`).

import type { ThreadTokenUsage } from './ThreadTokenUsage.js';

export type ThreadTokenUsageUpdatedNotification = {
  threadId: string;
  turnId: string;
  tokenUsage: ThreadTokenUsage;
};
