// GENERATED CODE! DO NOT MODIFY BY HAND!

// Generated by Codex CLI 0.146.0 (`codex app-server generate-ts`).

import type { TokenUsageBreakdown } from './TokenUsageBreakdown.js';

export type ThreadTokenUsage = {
  total: TokenUsageBreakdown;
  last: TokenUsageBreakdown;
  modelContextWindow: number | null;
};
