// GENERATED CODE! DO NOT MODIFY BY HAND!

// Generated by Codex CLI 0.147.0 (`codex app-server generate-ts`).

export type TokenUsageBreakdown = {
  totalTokens: number;
  inputTokens: number;
  cachedInputTokens: number;
  cacheWriteInputTokens: number;
  outputTokens: number;
  reasoningOutputTokens: number;
};
