// Embeds the Agents Hub web UI (fleet-hub/dist) into fleet-server so the
// compiled single binary can serve it under /fleet-hub with no files on disk.
//
// It copies fleet-hub/dist into server/hub-dist/ and generates
// server/hub-assets.generated.js — a module that imports every asset with
// `with { type: 'file' }`. `bun build --compile` embeds those bytes into the
// binary; at runtime hub-assets.js reads them via Bun.file(). Both outputs are
// gitignored and regenerated on every build.
//
// Usage:
//   bun run scripts/generate-hub-assets.ts            # from fleet-hub/dist
//   bun run scripts/generate-hub-assets.ts --hub ../elsewhere/dist
//
// Run automatically by scripts/build.ts before compiling.

import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dir, '..');
const SERVER_DIR = path.join(ROOT, 'server');
const EMBED_DIR = path.join(SERVER_DIR, 'hub-dist');
const MANIFEST_FILE = path.join(SERVER_DIR, 'hub-assets.generated.js');

function resolveHubDist(args: string[]): string {
  const flagIndex = args.indexOf('--hub');
  if (flagIndex !== -1 && args[flagIndex + 1]) {
    return path.resolve(process.cwd(), args[flagIndex + 1]);
  }
  return path.resolve(ROOT, '../fleet-hub/dist');
}

function walk(dir: string, base = dir): string[] {
  const out: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...walk(full, base));
    } else if (entry.isFile()) {
      out.push(path.relative(base, full));
    }
  }
  return out;
}

function writeEmptyManifest(reason: string): void {
  fs.writeFileSync(
    MANIFEST_FILE,
    `// AUTO-GENERATED by scripts/generate-hub-assets.ts — do not edit.\n` +
      `// Empty: ${reason}. The /fleet-hub route will report the UI as unavailable.\n` +
      `export const HUB_ASSETS = {};\n`
  );
}

export function generateHubAssets(hubDist: string): number {
  const indexHtml = path.join(hubDist, 'index.html');
  if (!fs.existsSync(indexHtml)) {
    console.warn(
      `⚠ No Agents Hub build at ${hubDist} — run "npm run build" in fleet-hub first.\n` +
        `  Continuing with an empty UI manifest; /fleet-hub will 404.`
    );
    fs.rmSync(EMBED_DIR, { recursive: true, force: true });
    writeEmptyManifest('fleet-hub/dist was missing at build time');
    return 0;
  }

  // Fresh copy so stale hashed assets from a previous build never linger.
  fs.rmSync(EMBED_DIR, { recursive: true, force: true });
  fs.cpSync(hubDist, EMBED_DIR, { recursive: true });

  // POSIX sub-paths (forward slashes) — these are URL keys and import
  // specifiers, never OS paths.
  const files = walk(EMBED_DIR).map((f) => f.split(path.sep).join('/'));
  files.sort();

  const imports: string[] = [];
  const entries: string[] = [];
  files.forEach((sub, i) => {
    const ref = `a${i}`;
    imports.push(`import ${ref} from './hub-dist/${sub}' with { type: 'file' };`);
    entries.push(`  ${JSON.stringify(sub)}: ${ref},`);
  });

  const manifest =
    `// AUTO-GENERATED by scripts/generate-hub-assets.ts — do not edit.\n` +
    `// Maps Agents Hub UI sub-paths to Bun-embedded file references so the\n` +
    `// compiled binary serves the UI under /fleet-hub with no files on disk.\n` +
    imports.join('\n') +
    `\n\nexport const HUB_ASSETS = {\n` +
    entries.join('\n') +
    `\n};\n`;

  fs.writeFileSync(MANIFEST_FILE, manifest);
  console.log(`  Embedded ${files.length} Agents Hub asset(s) from ${hubDist}`);
  return files.length;
}

if (import.meta.main) {
  const hubDist = resolveHubDist(process.argv.slice(2));
  generateHubAssets(hubDist);
}
